[package]

name = "piston-gfx_texture"
version = "0.0.3"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]
keywords = ["texture", "gfx", "graphics", "piston"]
description = "A Gfx texture representation that works nicely with Piston libraries"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/gfx_texture.git"
homepage = "https://github.com/pistondevelopers/gfx_texture"

[lib]

name = "gfx_texture"
path = "src/lib.rs"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"
#version = "~0.2.0"

[dependencies.piston-texture]
git = "https://github.com/PistonDevelopers/texture"
#version = "0.0.1"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
#version = "0.1.0"

